source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'VIPERS-CommandBus_Example', :exclusive => true do
  pod 'VIPERS-CommandBus', :path => '../'
end

target 'VIPERS-CommandBus_Tests', :exclusive => true do
  pod 'VIPERS-CommandBus', :path => '../'

  
end
